// ---------------------------------------------------------------------------
// "閱讀全文" (Read Full Text) button -> details modal wiring.
//
// AUTO-GENERATED by scripts/sync-details.mjs from ../details/*.md — do not
// hand-edit the array below, it will be overwritten on the next sync. Add a
// new article by dropping a "Page N.md" (or "Page N Left/Right/Top/Bottom.md"
// for a page with two buttons) into ../details/, then re-running
// `node scripts/sync-details.mjs`.
//
// The PDF renders each "閱讀全文" button's outline/arrow graphic into the
// page's background PNG (see ../../generate.py) — only the button's TEXT is
// real HTML (one of the absolutely-positioned `.t` divs in
// src/generated/fragments/pageN.html, id `p{N}-t{X}`).
// ---------------------------------------------------------------------------

export interface ReadMoreLink {
  /** Source PDF page number, for reference/debugging only. */
  page: number;
  /** Element id of the "閱讀全文" text span in that page's generated fragment. */
  elementId: string;
  /** Filename (without .md) under src/details/. */
  detailsFile: string;
}

export const readMoreLinks: ReadMoreLink[] = [
  { page: 6, elementId: 'p6-t1', detailsFile: 'page6readmore' },
  { page: 7, elementId: 'p7-t5', detailsFile: 'page7readmore' },
  { page: 34, elementId: 'p34-t2', detailsFile: 'page34readmore' },
  { page: 35, elementId: 'p35-t2', detailsFile: 'page35readmore' },
  { page: 36, elementId: 'p36-t2', detailsFile: 'page36readmore' },
  { page: 40, elementId: 'p40-t2', detailsFile: 'page40readmore' },
  { page: 41, elementId: 'p41-t2', detailsFile: 'page41readmore' },
  { page: 42, elementId: 'p42-t2', detailsFile: 'page42readmore' },
  { page: 43, elementId: 'p43-t2', detailsFile: 'page43readmore' },
  { page: 48, elementId: 'p48-t2', detailsFile: 'page48readmore' },
  { page: 49, elementId: 'p49-t2', detailsFile: 'page49readmore' },
  { page: 50, elementId: 'p50-t2', detailsFile: 'page50readmore' },
  { page: 51, elementId: 'p51-t2', detailsFile: 'page51readmore' },
  { page: 57, elementId: 'p57-t2', detailsFile: 'page57readmore' },
  { page: 58, elementId: 'p58-t2', detailsFile: 'page58readmore' },
  { page: 59, elementId: 'p59-t1', detailsFile: 'page59readmore' },
  { page: 60, elementId: 'p60-t2', detailsFile: 'page60readmore' },
  { page: 61, elementId: 'p61-t1', detailsFile: 'page61readmore' },
  { page: 63, elementId: 'p63-t1', detailsFile: 'page63readmore' },
  { page: 64, elementId: 'p64-t1', detailsFile: 'page64readmoreLeft' },
  { page: 64, elementId: 'p64-t2', detailsFile: 'page64readmoreRight' },
  { page: 65, elementId: 'p65-t22', detailsFile: 'page65readmoreLeft' },
  { page: 65, elementId: 'p65-t23', detailsFile: 'page65readmoreRight' },
  { page: 66, elementId: 'p66-t8', detailsFile: 'page66readmore' },
  { page: 67, elementId: 'p67-t8', detailsFile: 'page67readmore' },
  { page: 68, elementId: 'p68-t16', detailsFile: 'page68readmoreLeft' },
  { page: 68, elementId: 'p68-t17', detailsFile: 'page68readmoreRight' },
  { page: 69, elementId: 'p69-t14', detailsFile: 'page69readmoreLeft' },
  { page: 69, elementId: 'p69-t15', detailsFile: 'page69readmoreRight' },
  { page: 70, elementId: 'p70-t14', detailsFile: 'page70readmoreLeft' },
  { page: 70, elementId: 'p70-t15', detailsFile: 'page70readmoreRight' },
  { page: 71, elementId: 'p71-t15', detailsFile: 'page71readmoreLeft' },
  { page: 71, elementId: 'p71-t16', detailsFile: 'page71readmoreRight' },
  { page: 73, elementId: 'p73-t3', detailsFile: 'page73readmoreTop' },
  { page: 73, elementId: 'p73-t4', detailsFile: 'page73readmoreBottom' },
  { page: 74, elementId: 'p74-t3', detailsFile: 'page74readmoreTop' },
  { page: 74, elementId: 'p74-t4', detailsFile: 'page74readmoreBottom' },
  { page: 75, elementId: 'p75-t2', detailsFile: 'page75readmoreTop' },
  { page: 75, elementId: 'p75-t3', detailsFile: 'page75readmoreBottom' },
  { page: 76, elementId: 'p76-t3', detailsFile: 'page76readmoreTop' },
  { page: 76, elementId: 'p76-t4', detailsFile: 'page76readmoreBottom' },
  { page: 77, elementId: 'p77-t3', detailsFile: 'page77readmoreTop' },
  { page: 77, elementId: 'p77-t4', detailsFile: 'page77readmoreBottom' },
  { page: 78, elementId: 'p78-t4', detailsFile: 'page78readmoreTop' },
  { page: 78, elementId: 'p78-t5', detailsFile: 'page78readmoreBottom' },
  { page: 79, elementId: 'p79-t3', detailsFile: 'page79readmoreTop' },
  { page: 79, elementId: 'p79-t4', detailsFile: 'page79readmoreBottom' },
  { page: 81, elementId: 'p81-t3', detailsFile: 'page81readmore' },
  { page: 82, elementId: 'p82-t2', detailsFile: 'page82readmore' },
  { page: 83, elementId: 'p83-t2', detailsFile: 'page83readmore' },
  { page: 84, elementId: 'p84-t9', detailsFile: 'page84readmore' },
  { page: 85, elementId: 'p85-t10', detailsFile: 'page85readmore' },
  { page: 87, elementId: 'p87-t2', detailsFile: 'page87readmore' },
  { page: 88, elementId: 'p88-t2', detailsFile: 'page88readmore' },
  { page: 89, elementId: 'p89-t4', detailsFile: 'page89readmore' },
  { page: 90, elementId: 'p90-t2', detailsFile: 'page90readmore' },
];

export default readMoreLinks;
